# Generated by Django 5.2.13 on 2026-05-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.CharField(max_length=50, unique=True)),
                ('jobTitle', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
