# Generated by Django 6.0.5 on 2026-05-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobID', models.CharField(max_length=50)),
                ('applicantName', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('jobID', 'applicantName')},
            },
        ),
    ]
