# Generated by Django 5.2.13 on 2026-05-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
